### ISSUE TITLE
Shortcut editing error

### ISSUE THREAD

**Issue by gvenusleo** [yourselfhosted/slash#71]
### Describe the bug

When clicking to edit a shortcut, the following error occurs:

```text
Unexpected Application Error!
Cannot access 'ft' before initialization
ReferenceError: Cannot access 'ft' before initialization
    at http://{port}:{port}/assets/index-Jnb1qPNo.js:7342:98062
    at Rj (http://{port}:{port}/assets/index-Jnb1qPNo.js:69:26671)
    at Ik (http://{port}:{port}/assets/index-Jnb1qPNo.js:69:46527)
    at Xk (http://{port}:{port}/assets/index-Jnb1qPNo.js:69:45230)
    at Qk (http://{port}:{port}/assets/index-Jnb1qPNo.js:69:44208)
    at Fk (http://{port}:{port}/assets/index-Jnb1qPNo.js:69:40534)
    at jg (http://{port}:{port}/assets/index-Jnb1qPNo.js:67:3504)
    at http://{port}:{port}/assets/index-Jnb1qPNo.js:69:37650
```

### Steps to reproduce

Click on `Edit` .

### Expected behavior

Open the edit page correctly.

**Comment by boojack** [comment]
@gvenusleo It might be fixed with https://github.com/yourselfhosted/slash/commit/29043f63b6f3af277b68cf8f685460068c946fa6. Could you try pulling the latest branch?

**Comment by gvenusleo** [comment]
@boojack Yes, the issue was effectively resolved, thank you very much!
